export const stableLibraries = {
  // ============ EXPRESS.JS ECOSYSTEM ============
  expressBackend: [
    {
      name: "express",
      version: "^5.0.0",
      reason: "Core HTTP server framework - industry standard",
      usedBy: ["Uber", "PayPal", "Walmart", "Netflix"],
      documentation: "https://expressjs.com",
      setup: "npm install express",
    },
    {
      name: "typescript",
      version: "^5.0.0",
      reason: "Type safety for Express servers",
      usedBy: ["Microsoft", "Google", "Airbnb", "Slack"],
      documentation: "https://www.typescriptlang.org",
      setup: "npm install -D typescript @types/express @types/node",
    },
    {
      name: "prisma",
      version: "^5.0.0",
      reason: "Modern ORM with type-safe database access",
      usedBy: ["Shopify", "GitHub", "Coinbase", "Figma"],
      documentation: "https://www.prisma.io",
      setup: "npm install @prisma/client && npx prisma init",
    },
    {
      name: "mongoose",
      version: "^8.0.0",
      reason: "MongoDB ODM with schema validation",
      usedBy: ["Uber", "Spotify", "Airbnb"],
      documentation: "https://mongoosejs.com",
      setup: "npm install mongoose",
    },
    {
      name: "zod",
      version: "^3.22.0",
      reason: "TypeScript-first request validation",
      usedBy: ["Vercel", "Stripe", "Supabase"],
      documentation: "https://zod.dev",
      setup: "npm install zod",
    },
    {
      name: "joi",
      version: "^17.11.0",
      reason: "Data validation library - enterprise-grade",
      usedBy: ["PayPal", "Walmart"],
      documentation: "https://joi.dev",
      setup: "npm install joi",
    },
    {
      name: "jsonwebtoken",
      version: "^9.1.0",
      reason: "JWT authentication tokens",
      usedBy: ["Auth0", "Okta", "major enterprises"],
      documentation: "https://github.com/auth0/node-jsonwebtoken",
      setup: "npm install jsonwebtoken",
    },
    {
      name: "bcryptjs",
      version: "^2.4.3",
      reason: "Secure password hashing - production standard",
      usedBy: ["Every secure app"],
      documentation: "https://github.com/dcodeIO/bcrypt.js",
      setup: "npm install bcryptjs",
    },
    {
      name: "passport",
      version: "^0.7.0",
      reason: "Authentication middleware with 500+ strategies",
      usedBy: ["Microsoft", "Adobe", "major enterprises"],
      documentation: "http://www.passportjs.org",
      setup: "npm install passport passport-local passport-jwt",
    },
    {
      name: "cors",
      version: "^2.8.5",
      reason: "Cross-Origin Resource Sharing middleware",
      usedBy: ["All modern APIs"],
      documentation: "https://github.com/expressjs/cors",
      setup: "npm install cors",
    },
    {
      name: "dotenv",
      version: "^16.3.1",
      reason: "Environment variable management",
      usedBy: ["All production apps"],
      documentation: "https://github.com/motdotla/dotenv",
      setup: "npm install dotenv",
    },
    {
      name: "morgan",
      version: "^1.10.0",
      reason: "HTTP request logger for Express",
      usedBy: ["Most production apps"],
      documentation: "https://github.com/expressjs/morgan",
      setup: "npm install morgan",
    },
    {
      name: "helmet",
      version: "^7.1.0",
      reason: "Secure HTTP headers - security best practice",
      usedBy: ["All security-conscious apps"],
      documentation: "https://helmetjs.github.io",
      setup: "npm install helmet",
    },
    {
      name: "express-rate-limit",
      version: "^7.1.0",
      reason: "Rate limiting middleware to prevent abuse",
      usedBy: ["All production APIs"],
      documentation: "https://github.com/nfriedly/express-rate-limit",
      setup: "npm install express-rate-limit",
    },
    {
      name: "express-validator",
      version: "^7.0.0",
      reason: "Powerful input validation middleware",
      usedBy: ["Production applications"],
      documentation: "https://express-validator.github.io/docs",
      setup: "npm install express-validator",
    },
    {
      name: "compression",
      version: "^1.7.4",
      reason: "Gzip compression middleware for responses",
      usedBy: ["All performance-conscious apps"],
      documentation: "https://github.com/expressjs/compression",
      setup: "npm install compression",
    },
    {
      name: "socket.io",
      version: "^4.7.0",
      reason: "Real-time bidirectional communication",
      usedBy: ["Slack", "Discord alternatives", "real-time apps"],
      documentation: "https://socket.io",
      setup: "npm install socket.io",
    },
  ],

  // ============ REACT ECOSYSTEM ============
  reactFrontend: [
    {
      name: "react",
      version: "^18.2.0",
      reason: "Core UI library - industry standard",
      usedBy: ["Facebook", "Netflix", "Airbnb", "Instagram"],
      documentation: "https://react.dev",
      setup: "npx create-react-app my-app",
    },
    {
      name: "react-dom",
      version: "^18.2.0",
      reason: "React rendering for browser",
      usedBy: ["All React apps"],
      documentation: "https://react.dev",
      setup: "npm install react-dom",
    },
    {
      name: "typescript",
      version: "^5.0.0",
      reason: "Type safety for React components",
      usedBy: ["Airbnb", "Slack", "Shopify"],
      documentation: "https://www.typescriptlang.org",
      setup: "npm install -D typescript @types/react @types/react-dom",
    },
    {
      name: "react-router-dom",
      version: "^6.20.0",
      reason: "Client-side routing for SPAs",
      usedBy: ["Netflix", "Airbnb", "most React apps"],
      documentation: "https://reactrouter.com",
      setup: "npm install react-router-dom",
    },
    {
      name: "react-query",
      version: "^3.39.3",
      reason: "Server state management and data fetching",
      note: "Now TanStack Query",
      usedBy: ["Vercel", "Stripe", "thousands of apps"],
      documentation: "https://tanstack.com/query",
      setup: "npm install @tanstack/react-query",
    },
    {
      name: "zustand",
      version: "^4.4.0",
      reason: "Lightweight client state management",
      usedBy: ["Vercel", "modern startups"],
      documentation: "https://github.com/pmndrs/zustand",
      setup: "npm install zustand",
    },
    {
      name: "redux",
      version: "^4.2.0",
      reason: "Enterprise state management - predictable",
      usedBy: ["Facebook", "major enterprises"],
      documentation: "https://redux.js.org",
      setup: "npm install redux react-redux",
    },
    {
      name: "redux-toolkit",
      version: "^1.9.0",
      reason: "Modern Redux with less boilerplate",
      usedBy: ["Enterprise applications"],
      documentation: "https://redux-toolkit.js.org",
      setup: "npm install @reduxjs/toolkit react-redux",
    },
    {
      name: "jotai",
      version: "^2.5.0",
      reason: "Minimal atom-based state management",
      usedBy: ["Modern React apps"],
      documentation: "https://jotai.org",
      setup: "npm install jotai",
    },
    {
      name: "axios",
      version: "^1.6.0",
      reason: "HTTP client with interceptors",
      usedBy: ["Most React apps"],
      documentation: "https://axios-http.com",
      setup: "npm install axios",
    },
    {
      name: "react-hook-form",
      version: "^7.48.0",
      reason: "Performant form handling with minimal re-renders",
      usedBy: ["Modern React apps", "Stripe, Shopify"],
      documentation: "https://react-hook-form.com",
      setup: "npm install react-hook-form",
    },
    {
      name: "formik",
      version: "^2.4.0",
      reason: "Enterprise form management",
      usedBy: ["Large-scale applications"],
      documentation: "https://formik.org",
      setup: "npm install formik yup",
    },
    {
      name: "tailwindcss",
      version: "^3.3.0",
      reason: "Utility-first CSS framework",
      usedBy: ["Vercel", "modern startups", "Netflix"],
      documentation: "https://tailwindcss.com",
      setup: "npm install -D tailwindcss postcss autoprefixer",
    },
    {
      name: "styled-components",
      version: "^6.1.0",
      reason: "CSS-in-JS with dynamic styling",
      usedBy: ["Uber", "Airbnb", "Styled Components users"],
      documentation: "https://styled-components.com",
      setup: "npm install styled-components",
    },
    {
      name: "emotion",
      version: "^11.11.0",
      reason: "Performant CSS-in-JS library",
      usedBy: ["Facebook", "Chakra UI"],
      documentation: "https://emotion.sh",
      setup: "npm install @emotion/react @emotion/styled",
    },
    {
      name: "shadcn-ui",
      version: "latest",
      reason: "Copy-paste React component library with TailwindCSS",
      usedBy: ["Modern startups"],
      documentation: "https://ui.shadcn.com",
      setup: "npx shadcn-ui@latest init",
    },
    {
      name: "material-ui",
      version: "^5.14.0",
      reason: "Enterprise component library",
      usedBy: ["Google, major enterprises"],
      documentation: "https://mui.com",
      setup: "npm install @mui/material @emotion/react @emotion/styled",
    },
    {
      name: "chakra-ui",
      version: "^2.8.0",
      reason: "Accessible component library",
      usedBy: ["Startups, modern teams"],
      documentation: "https://chakra-ui.com",
      setup: "npm install @chakra-ui/react @emotion/react @emotion/styled",
    },
    {
      name: "swr",
      version: "^2.2.0",
      reason: "React Hook for data fetching - Vercel's library",
      usedBy: ["Vercel, modern React apps"],
      documentation: "https://swr.vercel.app",
      setup: "npm install swr",
    },
  ],

  // ============ NEXT.JS ECOSYSTEM ============
  nextjsFullstack: [
    {
      name: "next.js",
      version: "^14.0.0",
      reason: "React framework with SSR, SSG, API routes, app router",
      usedBy: ["Vercel", "TikTok", "Hulu", "Nike"],
      documentation: "https://nextjs.org",
      setup: "npx create-next-app@latest",
    },
    {
      name: "typescript",
      version: "^5.0.0",
      reason: "Type safety - highly recommended for Next.js",
      usedBy: ["All modern Next.js apps"],
      documentation: "https://www.typescriptlang.org",
      setup: "npx create-next-app@latest --typescript",
    },
    {
      name: "next-auth",
      version: "^4.24.0",
      reason: "Authentication for Next.js - OAuth, JWT, Sessions",
      usedBy: ["Vercel, hundreds of startups"],
      documentation: "https://next-auth.js.org",
      setup: "npm install next-auth",
    },
    {
      name: "prisma",
      version: "^5.0.0",
      reason: "Database ORM - official recommended choice",
      usedBy: ["Vercel, modern startups"],
      documentation: "https://www.prisma.io",
      setup: "npm install @prisma/client && npx prisma init",
    },
    {
      name: "drizzle-orm",
      version: "^0.29.0",
      reason: "Modern type-safe SQL ORM - lightweight alternative",
      usedBy: ["Modern startups"],
      documentation: "https://orm.drizzle.team",
      setup: "npm install drizzle-orm drizzle-kit",
    },
    {
      name: "react-hook-form",
      version: "^7.48.0",
      reason: "Form handling in Next.js apps",
      usedBy: ["Modern Next.js apps"],
      documentation: "https://react-hook-form.com",
      setup: "npm install react-hook-form",
    },
    {
      name: "zod",
      version: "^3.22.0",
      reason: "Request validation - pairs perfectly with Next.js",
      usedBy: ["Modern Next.js developers"],
      documentation: "https://zod.dev",
      setup: "npm install zod",
    },
    {
      name: "tailwindcss",
      version: "^3.3.0",
      reason: "Styling framework - official Next.js recommendation",
      usedBy: ["Most Next.js projects"],
      documentation: "https://tailwindcss.com",
      setup: "npx create-next-app@latest --tailwind",
    },
    {
      name: "shadcn-ui",
      version: "latest",
      reason: "Pre-built TailwindCSS components",
      usedBy: ["Modern Next.js projects"],
      documentation: "https://ui.shadcn.com",
      setup: "npx shadcn-ui@latest init",
    },
    {
      name: "zustand",
      version: "^4.4.0",
      reason: "Client state management for Next.js",
      usedBy: ["Modern Next.js developers"],
      documentation: "https://github.com/pmndrs/zustand",
      setup: "npm install zustand",
    },
    {
      name: "react-query",
      version: "^5.0.0",
      reason: "Server state management",
      note: "TanStack Query v5",
      usedBy: ["Modern data-heavy apps"],
      documentation: "https://tanstack.com/query",
      setup: "npm install @tanstack/react-query",
    },
    {
      name: "axios",
      version: "^1.6.0",
      reason: "HTTP client for Next.js",
      usedBy: ["Most Next.js apps"],
      documentation: "https://axios-http.com",
      setup: "npm install axios",
    },
    {
      name: "next-intl",
      version: "^2.21.0",
      reason: "Internationalization for Next.js",
      usedBy: ["Global applications"],
      documentation: "https://next-intl-docs.vercel.app",
      setup: "npm install next-intl",
    },
    {
      name: "iron-session",
      version: "^8.4.0",
      reason: "Encrypted session management - lightweight auth",
      usedBy: ["Next.js apps needing sessions"],
      documentation: "https://github.com/vvo/iron-session",
      setup: "npm install iron-session",
    },
    {
      name: "next-safe-action",
      version: "^7.0.0",
      reason: "Type-safe Server Actions with validation",
      usedBy: ["Modern Next.js 13+ apps"],
      documentation: "https://next-safe-action.js.org",
      setup: "npm install next-safe-action",
    },
  ],

  // ============ DATABASE LAYER ============
  databases: [
    {
      name: "prisma",
      type: "ORM",
      databases: ["PostgreSQL", "MySQL", "SQLite", "MongoDB"],
      reason: "Type-safe database access with auto-migrations",
      usedBy: ["Vercel", "GitHub", "Shopify", "Figma"],
      documentation: "https://www.prisma.io",
      setup: "npm install @prisma/client && npx prisma init",
    },
    {
      name: "drizzle-orm",
      type: "ORM",
      databases: ["PostgreSQL", "MySQL", "SQLite"],
      reason: "Lightweight, type-safe SQL ORM",
      usedBy: ["Modern startups"],
      documentation: "https://orm.drizzle.team",
      setup: "npm install drizzle-orm drizzle-kit",
    },
    {
      name: "mongoose",
      type: "ODM",
      database: "MongoDB",
      reason: "Schema validation for MongoDB",
      usedBy: ["Uber", "Spotify", "major enterprises"],
      documentation: "https://mongoosejs.com",
      setup: "npm install mongoose",
    },
    {
      name: "typeorm",
      type: "ORM",
      databases: ["PostgreSQL", "MySQL", "SQLite"],
      reason: "Enterprise ORM with decorators",
      usedBy: ["NestJS projects"],
      documentation: "https://typeorm.io",
      setup: "npm install typeorm",
    },
    {
      name: "sequelize",
      type: "ORM",
      databases: ["PostgreSQL", "MySQL", "SQLite"],
      reason: "Promise-based ORM - mature",
      usedBy: ["Legacy and modern apps"],
      documentation: "https://sequelize.org",
      setup: "npm install sequelize",
    },
  ],

  // ============ TESTING FRAMEWORKS ============
  testing: [
    {
      name: "vitest",
      version: "^1.0.0",
      reason: "Lightning-fast unit testing - Vite native",
      usedBy: ["Modern frameworks"],
      documentation: "https://vitest.dev",
      setup: "npm install -D vitest",
    },
    {
      name: "jest",
      version: "^29.7.0",
      reason: "Zero-config testing platform - industry standard",
      usedBy: ["Facebook, major enterprises"],
      documentation: "https://jestjs.io",
      setup: "npm install -D jest @types/jest",
    },
    {
      name: "@testing-library/react",
      version: "^14.1.0",
      reason: "User-centric React component testing",
      usedBy: ["Modern React apps"],
      documentation: "https://testing-library.com",
      setup: "npm install -D @testing-library/react @testing-library/jest-dom",
    },
    {
      name: "cypress",
      version: "^13.6.0",
      reason: "Developer-friendly E2E testing",
      usedBy: ["Modern development teams"],
      documentation: "https://cypress.io",
      setup: "npm install -D cypress",
    },
    {
      name: "playwright",
      version: "^1.40.0",
      reason: "Cross-browser E2E testing - most powerful",
      usedBy: ["Microsoft, major enterprises"],
      documentation: "https://playwright.dev",
      setup: "npm install -D @playwright/test",
    },
  ],

  // ============ UTILITIES & HELPERS ============
  utilities: [
    {
      name: "axios",
      version: "^1.6.0",
      reason: "HTTP client with interceptors",
      usedBy: ["Most modern apps"],
      documentation: "https://axios-http.com",
      setup: "npm install axios",
    },
    {
      name: "lodash",
      version: "^4.17.21",
      reason: "Utility library - use lodash-es for tree-shaking",
      usedBy: ["Most JavaScript projects"],
      documentation: "https://lodash.com",
      setup: "npm install lodash-es",
    },
    {
      name: "dayjs",
      version: "^1.11.0",
      reason: "Lightweight date manipulation (2KB vs 67KB moment)",
      usedBy: ["Modern apps"],
      documentation: "https://day.js.org",
      setup: "npm install dayjs",
    },
    {
      name: "date-fns",
      version: "^2.30.0",
      reason: "Functional date manipulation library",
      usedBy: ["Modern JavaScript apps"],
      documentation: "https://date-fns.org",
      setup: "npm install date-fns",
    },
    {
      name: "uuid",
      version: "^9.0.0",
      reason: "UUID generation - standard library",
      usedBy: ["All apps needing IDs"],
      documentation: "https://github.com/uuidjs/uuid",
      setup: "npm install uuid",
    },
    {
      name: "clsx",
      version: "^2.0.0",
      reason: "Utility for conditional classNames",
      usedBy: ["React component libraries"],
      documentation: "https://github.com/lukeed/clsx",
      setup: "npm install clsx",
    },
    {
      name: "classnames",
      version: "^2.3.0",
      reason: "Conditional CSS class names",
      usedBy: ["React apps"],
      documentation: "https://github.com/JedWatson/classnames",
      setup: "npm install classnames",
    },
  ],
};
